/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriterRouteImport } from './routes/writer'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SocialManagementRouteImport } from './routes/social-management'
import { Route as SidequestRouteImport } from './routes/sidequest'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PosterStudiesRouteImport } from './routes/poster-studies'
import { Route as ModelRouteImport } from './routes/model'
import { Route as InteractiveRouteImport } from './routes/interactive'
import { Route as HanbyulBrandRouteImport } from './routes/hanbyul-brand'
import { Route as FliersRouteImport } from './routes/fliers'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosterStudiesIndexRouteImport } from './routes/poster-studies.index'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as PosterStudiesSlugRouteImport } from './routes/poster-studies.$slug'

const WriterRoute = WriterRouteImport.update({
  id: '/writer',
  path: '/writer',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialManagementRoute = SocialManagementRouteImport.update({
  id: '/social-management',
  path: '/social-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SidequestRoute = SidequestRouteImport.update({
  id: '/sidequest',
  path: '/sidequest',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterStudiesRoute = PosterStudiesRouteImport.update({
  id: '/poster-studies',
  path: '/poster-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveRoute = InteractiveRouteImport.update({
  id: '/interactive',
  path: '/interactive',
  getParentRoute: () => rootRouteImport,
} as any)
const HanbyulBrandRoute = HanbyulBrandRouteImport.update({
  id: '/hanbyul-brand',
  path: '/hanbyul-brand',
  getParentRoute: () => rootRouteImport,
} as any)
const FliersRoute = FliersRouteImport.update({
  id: '/fliers',
  path: '/fliers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterStudiesIndexRoute = PosterStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosterStudiesRoute,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterStudiesSlugRoute = PosterStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PosterStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/fliers': typeof FliersRoute
  '/hanbyul-brand': typeof HanbyulBrandRoute
  '/interactive': typeof InteractiveRoute
  '/model': typeof ModelRoute
  '/poster-studies': typeof PosterStudiesRouteWithChildren
  '/services': typeof ServicesRoute
  '/sidequest': typeof SidequestRoute
  '/social-management': typeof SocialManagementRoute
  '/work': typeof WorkRoute
  '/writer': typeof WriterRoute
  '/poster-studies/$slug': typeof PosterStudiesSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/poster-studies/': typeof PosterStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/fliers': typeof FliersRoute
  '/hanbyul-brand': typeof HanbyulBrandRoute
  '/interactive': typeof InteractiveRoute
  '/model': typeof ModelRoute
  '/services': typeof ServicesRoute
  '/sidequest': typeof SidequestRoute
  '/social-management': typeof SocialManagementRoute
  '/work': typeof WorkRoute
  '/writer': typeof WriterRoute
  '/poster-studies/$slug': typeof PosterStudiesSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/poster-studies': typeof PosterStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/fliers': typeof FliersRoute
  '/hanbyul-brand': typeof HanbyulBrandRoute
  '/interactive': typeof InteractiveRoute
  '/model': typeof ModelRoute
  '/poster-studies': typeof PosterStudiesRouteWithChildren
  '/services': typeof ServicesRoute
  '/sidequest': typeof SidequestRoute
  '/social-management': typeof SocialManagementRoute
  '/work': typeof WorkRoute
  '/writer': typeof WriterRoute
  '/poster-studies/$slug': typeof PosterStudiesSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/poster-studies/': typeof PosterStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/fliers'
    | '/hanbyul-brand'
    | '/interactive'
    | '/model'
    | '/poster-studies'
    | '/services'
    | '/sidequest'
    | '/social-management'
    | '/work'
    | '/writer'
    | '/poster-studies/$slug'
    | '/project/$slug'
    | '/poster-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/fliers'
    | '/hanbyul-brand'
    | '/interactive'
    | '/model'
    | '/services'
    | '/sidequest'
    | '/social-management'
    | '/work'
    | '/writer'
    | '/poster-studies/$slug'
    | '/project/$slug'
    | '/poster-studies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/fliers'
    | '/hanbyul-brand'
    | '/interactive'
    | '/model'
    | '/poster-studies'
    | '/services'
    | '/sidequest'
    | '/social-management'
    | '/work'
    | '/writer'
    | '/poster-studies/$slug'
    | '/project/$slug'
    | '/poster-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  FliersRoute: typeof FliersRoute
  HanbyulBrandRoute: typeof HanbyulBrandRoute
  InteractiveRoute: typeof InteractiveRoute
  ModelRoute: typeof ModelRoute
  PosterStudiesRoute: typeof PosterStudiesRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SidequestRoute: typeof SidequestRoute
  SocialManagementRoute: typeof SocialManagementRoute
  WorkRoute: typeof WorkRoute
  WriterRoute: typeof WriterRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writer': {
      id: '/writer'
      path: '/writer'
      fullPath: '/writer'
      preLoaderRoute: typeof WriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-management': {
      id: '/social-management'
      path: '/social-management'
      fullPath: '/social-management'
      preLoaderRoute: typeof SocialManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidequest': {
      id: '/sidequest'
      path: '/sidequest'
      fullPath: '/sidequest'
      preLoaderRoute: typeof SidequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster-studies': {
      id: '/poster-studies'
      path: '/poster-studies'
      fullPath: '/poster-studies'
      preLoaderRoute: typeof PosterStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive': {
      id: '/interactive'
      path: '/interactive'
      fullPath: '/interactive'
      preLoaderRoute: typeof InteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hanbyul-brand': {
      id: '/hanbyul-brand'
      path: '/hanbyul-brand'
      fullPath: '/hanbyul-brand'
      preLoaderRoute: typeof HanbyulBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fliers': {
      id: '/fliers'
      path: '/fliers'
      fullPath: '/fliers'
      preLoaderRoute: typeof FliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster-studies/': {
      id: '/poster-studies/'
      path: '/'
      fullPath: '/poster-studies/'
      preLoaderRoute: typeof PosterStudiesIndexRouteImport
      parentRoute: typeof PosterStudiesRoute
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster-studies/$slug': {
      id: '/poster-studies/$slug'
      path: '/$slug'
      fullPath: '/poster-studies/$slug'
      preLoaderRoute: typeof PosterStudiesSlugRouteImport
      parentRoute: typeof PosterStudiesRoute
    }
  }
}

interface PosterStudiesRouteChildren {
  PosterStudiesSlugRoute: typeof PosterStudiesSlugRoute
  PosterStudiesIndexRoute: typeof PosterStudiesIndexRoute
}

const PosterStudiesRouteChildren: PosterStudiesRouteChildren = {
  PosterStudiesSlugRoute: PosterStudiesSlugRoute,
  PosterStudiesIndexRoute: PosterStudiesIndexRoute,
}

const PosterStudiesRouteWithChildren = PosterStudiesRoute._addFileChildren(
  PosterStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  FliersRoute: FliersRoute,
  HanbyulBrandRoute: HanbyulBrandRoute,
  InteractiveRoute: InteractiveRoute,
  ModelRoute: ModelRoute,
  PosterStudiesRoute: PosterStudiesRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SidequestRoute: SidequestRoute,
  SocialManagementRoute: SocialManagementRoute,
  WorkRoute: WorkRoute,
  WriterRoute: WriterRoute,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
