/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SidequestRouteImport } from './routes/sidequest'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as InteractiveRouteImport } from './routes/interactive'
import { Route as FliersRouteImport } from './routes/fliers'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SidequestRoute = SidequestRouteImport.update({
  id: '/sidequest',
  path: '/sidequest',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveRoute = InteractiveRouteImport.update({
  id: '/interactive',
  path: '/interactive',
  getParentRoute: () => rootRouteImport,
} as any)
const FliersRoute = FliersRouteImport.update({
  id: '/fliers',
  path: '/fliers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/fliers': typeof FliersRoute
  '/interactive': typeof InteractiveRoute
  '/services': typeof ServicesRoute
  '/sidequest': typeof SidequestRoute
  '/work': typeof WorkRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/fliers': typeof FliersRoute
  '/interactive': typeof InteractiveRoute
  '/services': typeof ServicesRoute
  '/sidequest': typeof SidequestRoute
  '/work': typeof WorkRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/fliers': typeof FliersRoute
  '/interactive': typeof InteractiveRoute
  '/services': typeof ServicesRoute
  '/sidequest': typeof SidequestRoute
  '/work': typeof WorkRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/fliers'
    | '/interactive'
    | '/services'
    | '/sidequest'
    | '/work'
    | '/project/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/fliers'
    | '/interactive'
    | '/services'
    | '/sidequest'
    | '/work'
    | '/project/$slug'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/fliers'
    | '/interactive'
    | '/services'
    | '/sidequest'
    | '/work'
    | '/project/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  FliersRoute: typeof FliersRoute
  InteractiveRoute: typeof InteractiveRoute
  ServicesRoute: typeof ServicesRoute
  SidequestRoute: typeof SidequestRoute
  WorkRoute: typeof WorkRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidequest': {
      id: '/sidequest'
      path: '/sidequest'
      fullPath: '/sidequest'
      preLoaderRoute: typeof SidequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive': {
      id: '/interactive'
      path: '/interactive'
      fullPath: '/interactive'
      preLoaderRoute: typeof InteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fliers': {
      id: '/fliers'
      path: '/fliers'
      fullPath: '/fliers'
      preLoaderRoute: typeof FliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  FliersRoute: FliersRoute,
  InteractiveRoute: InteractiveRoute,
  ServicesRoute: ServicesRoute,
  SidequestRoute: SidequestRoute,
  WorkRoute: WorkRoute,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
